const TRACK_FIRST_INDEX = 0;
const FULL_PERCENTAGE = 100;
const TRACK_INCREMENT_INDEX = 1;
const PROGRESS_BAR = '--player-progress';

export {
  FULL_PERCENTAGE,
  PROGRESS_BAR,
  TRACK_FIRST_INDEX,
  TRACK_INCREMENT_INDEX,
};
export {
  DURATION_UNIT,
  TRACK_SKIP_SECONDS,
  TRACK_START_TIME,
} from 'shared/build/index.js';
